services:
  - type: web
    name: your-api-name
    env: ruby
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_ENV
        value: production

databases:
  - name: postgres
    ipAllowList: [] 